image: python:3.7

include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - generate
  - deploy

# Generate documentation and stores the artifact under /generated/html
generate-documentation:
  stage: generate
  image: python
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_TAG
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  script: sphinx-build -T --keep-going -b html -c ./doc/source -D language=en ./doc/source generated/html
  before_script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - generated/html
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-staging-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-dev

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-production-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-prod


# Build image for annotation pipeline
update-annotation-image:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      changes:
        - annotation/Dockerfile
        - .gitlab-ci.yml
      when: on_success
  before_script:
    - echo $GITLAB_DEPLOY_TOKEN and $GITLAB_DEPLOY_PASSWORD
    - echo $CI_DEPLOY_TOKEN and $CI_DEPLOY_PASSWORD
    - echo $KANIKO_EXTRA_ARGS
  variables:
    BUILD_PATH: $CI_PROJECT_DIR/annotation
    GITLAB_DEPLOY_TOKEN: $GITLAB_DEPLOY_TOKEN
    GITLAB_DEPLOY_PASSWORD: $GITLAB_DEPLOY_PASSWORD
    CI_DEPLOY_TOKEN: $CI_DEPLOY_TOKEN
    CI_DEPLOY_PASSWORD: $CI_DEPLOY_PASSWORD
    KANIKO_EXTRA_ARGS: "--build-arg GITLAB_DEPLOY_TOKEN=$GITLAB_DEPLOY_TOKEN  --build-arg GITLAB_DEPLOY_PASSWORD=$GITLAB_DEPLOY_PASSWORD  --build-arg CI_DEPLOY_TOKEN=$CI_DEPLOY_TOKEN  --build-arg CI_DEPLOY_PASSWORD=$CI_DEPLOY_PASSWORD"
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi
