image: python:3.7

include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - generate
  - deploy
  - convert_and_deployToBB5

# Generate documentation and stores the artifact under /generated/html
generate-documentation:
  stage: generate
  image: python
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_TAG
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  script: sphinx-build -T --keep-going -b html -c ./doc/source -D language=en ./doc/source generated/html
  before_script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - generated/html
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-staging-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  variables:
    BUILD_PATH: $CI_PROJECT_DIR/doc
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-dev

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-production-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    BUILD_PATH: $CI_PROJECT_DIR/doc
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-prod


# Build image for pipeline
update-pipeline-image:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      changes:
        - snakefile
        - Dockerfile
        - .gitlab-ci.yml
        - .keycloak_config.yml
      when: on_success
  variables:
    BUILD_PATH: $CI_PROJECT_DIR
    KANIKO_EXTRA_ARGS: "--build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN"
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

convert_and_deploy_job:
  stage:
    convert_and_deployToBB5
  needs: ["update-pipeline-image"]
  when: on_success
  tags:
    - bb5_map
  variables:
    bb5_constraint: nvme
    bb5_cpus_per_task: 2
    bb5_memory: 4G
    bb5_duration: "10:00"
  script:
    - bash convert_singularity_image.sh
