image: python:3.7

include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - generate
  - deploy

# Generate documentation and stores the artifact under /generated/html
generate-documentation:
  stage: generate
  image: python
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_TAG
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  script: sphinx-build -T --keep-going -b html -c ./doc/source -D language=en ./doc/source generated/html
  before_script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - generated/html
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi


# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-staging-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: "docker-registry-default.ocp.bbp.epfl.ch/bbp-dke-staging/bba-pipeline-documentation"
    CI_REGISTRY_USER: $CI_REGISTRY_USER_STAGING
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD_STAGING
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi


# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-production-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: "docker-registry-default.ocp.bbp.epfl.ch/bbp-dke-production/bba-pipeline-documentation"
    CI_REGISTRY_USER: $CI_REGISTRY_USER_PRODUCTION
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD_PRODUCTION
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi
