image: "python:3.6"

stages:
  - generate

before_script:
  - pip install -r requirements.txt

# GENERATE STAGE

# Generate documentation and stores the artifact under /generated/html
generate-documentation:
  stage: generate
  image: python
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  script: sphinx-build -T --keep-going -b html -c ./doc/source -D language=en ./doc/source generated/html
  artifacts:
    paths:
      - generated/html
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi


