image: python:3.7

include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - generate
  - deploy
  - test

# Generate documentation and stores the artifact under /generated/html
generate-documentation:
  stage: generate
  image: python
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_TAG
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  script: sphinx-build -T --keep-going -b html -c ./doc/source -D language=en ./doc/source generated/html
  before_script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - generated/html
  variables:
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-staging-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
      - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        when: on_success
      - if: $CI_MERGE_REQUEST_IID
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /DRAFT$/
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-dev

# Executes deployment of project documentation to bbp-dke-staging Openshift
deploy-documentation-in-production-openshift:
  stage: deploy
  extends: .build-image-using-kaniko
  dependencies:
    - generate-documentation
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    KANIKO_EXTRA_ARGS: "--build-arg GENERATED_DOCS_PATH=generated/html"
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sphinx-documentation-prod


# Build image for annotation pipeline
update-annotation-image:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      changes:
        - annotation/Dockerfile
        - .gitlab-ci.yml
      when: on_success
  variables:
    BUILD_PATH: $CI_PROJECT_DIR/annotation
    KANIKO_EXTRA_ARGS: "--build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN"
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi

test_singularity:
  stage: test
  tags:
    - bb5
  script:
    - module load unstable
    - module use /gpfs/bbp.cscs.ch/apps/hpc/singularity/modules/linux-rhel7-x86_64
    - module load singularityce
    - singularity --version
