include:
  - project: dke/apps/templates/generate-deploy-docs-template
    file: .gitlab-ci.yml

image: "python:3.6"

stages:
  - generate-doc

before_script:
  - pip install -r requirements.txt

generate_documentation:
  stage: generate-doc
  extends: generate-documentation
  script:
    - sphinx-build -T --keep-going -b html -d _build/doctrees -c ./docs/source -D language=en ./docs/source generated/html

