WORKING_DIR: "/Users/lurie/Documents/BBP/data/pipeline_working_dir"
NEXUS_ENV: "https://bbp.epfl.ch/nexus/v1/"
NEXUS_ORG: "bbp"
NEXUS_PROJ: "atlas"
NEXUS_TOKEN_FILE: "/Users/lurie/Documents/BBP/data/pipeline_working_dir/token.txt"
RESOLUTION: "25"
