WORKING_DIR: ../pipeline_working_dir
NEXUS_ENV: "https://bbp.epfl.ch/nexus/v1/"
NEXUS_ORG: "bbp"
NEXUS_PROJ: "atlas"
NEXUS_TOKEN_FILE: ../nexus/token.txt
RESOLUTION: "25"
NEXUS_IDS_FILE: ./nexus_ids.json
RULES_CONFIG_DIR_TEMPLATES: ./rules_config_dir_templates