WORKING_DIR: leaves_only
REPO_PATH: .
KEYCLOAK_CONFIG: keycloak_config.yml
NEXUS_IDS_FILE: nexus_ids.json
FORGE_CONFIG: forge-config.yml
RULES_CONFIG_DIR_TEMPLATES: rules_config_dir_templates
ATLAS_CONFIG_PATH: atlasrelease_config_path.json
NEW_ATLAS: False
RESOLUTION: "25"
EXPORT_MESHES: True
MODULES_VERBOSE: True
RESOURCE_TAG: "leaves-only_atlas"  # put None to generate an automatic tag corresponding to the timestamp
DISPLAY_HELP: False

define: &prod_url "https://bbp.epfl.ch/nexus/v1"
#define: &staging_url "https://staging.nexus.ocp.bbp.epfl.ch/v1"
define: &staging_url "https://staging.nise.bbp.epfl.ch/nexus/v1"

IS_PROD_ENV: False
ATLAS_RELEASE_NAME: "Blue Brain Atlas"
ATLAS_RELEASE_DESCRIPTION: "The official Atlas of the Blue Brain Project"

# The pipeline will fetch the necessary datasets from:
#NEXUS_ATLAS_ENV: *prod_url
NEXUS_ATLAS_ENV: *staging_url
NEXUS_ATLAS_ORG: "bbp"
NEXUS_ATLAS_PROJ: "atlas"
NEXUS_ONTOLOGY_ORG: "neurosciencegraph"
NEXUS_ONTOLOGY_PROJ: "datamodels"

# The pipeline will push the generated datasets into:
NEXUS_DESTINATION_ENV: *staging_url
NEXUS_DESTINATION_ORG: "bbp"
NEXUS_DESTINATION_PROJ: "atlas"

CELL_COMPOSITION_NAME: "Cell Composition from Blue Brain Atlas"
CELL_COMPOSITION_SUMMARY_NAME: "Cell Composition Summary from Blue Brain Atlas"
CELL_COMPOSITION_VOLUME_NAME: "Cell Composition Volume from Blue Brain Atlas"
