HierarchyJson:
  hierarchy: {WORKING_DIR}/hierarchy.json
  hierarchy_l23split: {WORKING_DIR}/hierarchy_l23split.json
  mba_hierarchy_l23split: {WORKING_DIR}/mba_hierarchy_l23split.json
GeneratedDatasetPath:
  VolumetricFile:
    average_template_25: {WORKING_DIR}/average_template_25.nrrd
    annotation_v2_withfiber: {WORKING_DIR}/annotation_v2_withfiber.nrrd
    annotation_v2v3_hybrid: {WORKING_DIR}/annotation_v2v3_hybrid.nrrd
    annotation_ccfv2_l23split: {WORKING_DIR}/annotation_ccfv2_l23split.nrrd
    annotation_ccfv3_l23split: {WORKING_DIR}/annotation_ccfv3_l23split.nrrd
    annotation_hybrid: {WORKING_DIR}/annotation_hybrid.nrrd
    annotation_hybrid_l23split: {WORKING_DIR}/annotation_hybrid_l23split.nrrd
    hemispheres_ccfv2_l23split: {WORKING_DIR}/hemispheres_annotation_ccfv2_l23split.nrrd
    hemispheres_ccfv3_l23split: {WORKING_DIR}/hemispheres_annotation_ccfv3_l23split.nrrd
    interpolated_direction_vectors_isocortex_ccfv2: fullv2_annotation/interpolated_direction_vectors_isocortex_ccfv2.nrrd
    direction_vectors_isocortex_ccfv2: {WORKING_DIR}/direction_vectors_isocortex_ccfv2.nrrd
    direction_vectors_isocortex_ccfv3: {WORKING_DIR}/direction_vectors_isocortex_ccfv3.nrrd
    cell_orientations_ccfv2: {WORKING_DIR}/cell_orientations_ccfv2.nrrd
    cell_orientations_ccfv3: {WORKING_DIR}/cell_orientations_ccfv3.nrrd
    cell_orientations_hybrid: {WORKING_DIR}/cell_orientations_hybrid.nrrd
    placement_hints_ccfv2_l23split: {WORKING_DIR}/placement_hints_ccfv2_l23split
    placement_hints_ccfv3_l23split: {WORKING_DIR}/placement_hints_ccfv3_l23split
    placement_hints_hybrid_l23split: {WORKING_DIR}/placement_hints_hybrid_l23split
    overall_cell_density_ccfv2_correctednissl: {WORKING_DIR}/overall_cell_density_ccfv2_correctednissl.nrrd
    overall_cell_density_ccfv2_l23split_correctednissl: {WORKING_DIR}/overall_cell_density_ccfv2_l23split_correctednissl
    overall_cell_density_hybrid_l23split_correctednissl: {WORKING_DIR}/overall_cell_density_hybrid_l23split_correctednissl.nrrd
    cell_densities_hybrid: {WORKING_DIR}/cell_densities_hybrid
    cell_densities_hybrid_l23split_correctednissl: {WORKING_DIR}/cell_densities_hybrid_l23split_correctednissl
    cell_densities_ccfv2: {WORKING_DIR}/cell_densities_ccfv2
    cell_densities_ccfv2_correctednissl: {WORKING_DIR}/cell_densities_ccfv2_correctednissl
    cell_densities_ccfv2_l23split_correctednissl: {WORKING_DIR}/cell_densities_ccfv2_l23split_correctednissl
    cell_densities_ccfv3_correctednissl: {WORKING_DIR}/cell_densities_ccfv3_correctednissl
    glia_cell_densities_l23split_transplant_correctednissl: {WORKING_DIR}/glia_cell_densities_l23split_transplant_correctednissl
    neuron_densities_hybrid: {WORKING_DIR}/neuron_densities_hybrid
    neuron_densities_ccfv2: {WORKING_DIR}/neuron_densities_ccfv2
    neuron_densities_ccfv2_correctednissl: {WORKING_DIR}/neuron_densities_ccfv2_correctednissl
    inhibitory_neuron_densities_linprog_ccfv2_correctednissl: {WORKING_DIR}/inhibitory_neuron_densities_linprog_ccfv2_correctednissl
    inhibitory_neuron_densities_linprog_ccfv2_l23split_correctednissl: {WORKING_DIR}/inhibitory_neuron_densities_linprog_ccfv2_l23split_correctednissl
    inhibitory_neuron_densities_linprog_hybrid_l23split_correctednissl: {WORKING_DIR}/ inhibitory_neuron_densities_linprog_hybrid_l23split_correctednissl
    inhibitory_neuron_densities_preserveprop_ccfv2_correctednissl: {WORKING_DIR}/inhibitory_neuron_densities_preserveprop_ccfv2_correctednissl
    inhibitory_neuron_densities_linprog_l23split_transplant_correctednissl: {WORKING_DIR}/inhibitory_neuron_densities_linprog_l23split_transplant_correctednissl
    mtypes_densities_profile_ccfv2_correctednissl: {WORKING_DIR}/mtypes_densities_profile_ccfv2_correctednissl
    mtypes_densities_profile_hybrid_l23split_correctednissl: {WORKING_DIR}/mtypes_densities_profile_hybrid_l23split_correctednissl
    mtypes_densities_probability_map_ccfv2_correctednissl: {WORKING_DIR}/mtypes_densities_probability_map_ccfv2_correctednissl
    mtypes_densities_probability_map_ccfv2_l23split_correctednissl: {WORKING_DIR}/mtypes_densities_probability_map_ccfv2_l23split_correctednissl
    mtypes_densities_probability_map_hybrid_l23split_correctednissl: {WORKING_DIR}/mtypes_densities_probability_map_hybrid_l23split_correctednissl
    mtypes_densities_probability_map_transplant_correctednissl: {WORKING_DIR}/mtypes_densities_probability_map_transplant_correctednissl
    mtypes_densities_probability_map_l23split_transplant_correctednissl: {WORKING_DIR}/mtypes_densities_probability_map_l23split_transplant_correctednissl
    brain_region_mask_ccfv2_l23split: {WORKING_DIR}/brain_region_mask_ccfv2_l23split
    brain_region_mask_ccfv3_l23split: {WORKING_DIR}/brain_region_mask_ccfv3_l23split
    brain_region_masks_hybrid: {WORKING_DIR}/brain_region_masks_hybrid
    brain_region_masks_hybrid_l23split: {WORKING_DIR}/brain_region_masks_hybrid_l23split
  MeshFile:
    brain_region_meshes_ccfv2_l23split: {WORKING_DIR}/brain_region_mesh_ccfv2_l23split
    brain_region_meshes_ccfv3_l23split: {WORKING_DIR}/brain_region_mesh_ccfv3_l23split
    brain_region_meshes_hybrid: {WORKING_DIR}/brain_region_meshes_v2v3_hybrid
    brain_region_meshes_hybrid_l23split: {WORKING_DIR}/brain_region_meshes_hybrid_l23split
  CellRecordsFile:
    cell_records_sonata: {WORKING_DIR}/cell_records_sonata.h5
  MetadataFile:
    metadata_parcellations_ccfv2_l23split: {WORKING_DIR}/metadata_parcellations_ccfv2_l23split.json
    metadata_parcellations_ccfv3_l23split: {WORKING_DIR}/metadata_parcellations_ccfv3_l23split.json
